### ISSUE TITLE
Send only to one user when in the network

### ISSUE THREAD

**Issue by KonVas** [muellmusik/Utopia#22]
Is there a method to send only to specific users when they are on the network, for example, how can I do something liek this:
`~addrBook[\konstantinos].send('/el1', "Hello");`

This doesn't seem to be working.

**Comment by muellmusik** [comment]
That should work I think.

**Comment by muellmusik** [comment]
sendMsg

**Comment by adcxyz** [comment]
I just tested this, and it works: 
```
OSCdef(\test, { |msg| 
	msg.postcs;
}, "/test123");

~addrBook.send(~addrBook.me.name, "/test123", 4, 5, 6)
```

**Comment by muellmusik** [comment]
Yes that’s right. sendMsg is the method in Peer.

**Comment by KonVas** [comment]
Thanks
