### ISSUE TITLE
addrBook.me is not kept in sync with the peer's own entry in the address book

### ISSUE THREAD

**Issue by sidechained** [muellmusik/Utopia#3]
Hi Scott (and maybe Julian?),

I'm working with Jonas here in Guangzhou on a new project using two laptops and two BeagleBoards running Utopia for networking. Right now we're doing some basic ad hoc registration with the two laptops and then trying to share server addresses on top of that with an OSCObjectSpace, just to be able to play on each other's servers.

The OSCObjectSpace sync method doesn't work as expected. It tries to look for the first non-local player and make a copy of their object space, but this test fails because the peer contained in the address book has a remote IP, whereas the peer returned by 'addrBook.me' has a local IP. It seems like the latter should automatically be kept in sync with the former, is that right?

For now, to get around the problem we simply changed from this:

```
syncAddr = addr ?? { addrBook.peers.reject({|peer| peer == addrBook.me }).detect({|peer| peer.online }).addr };
```

To this:

```
syncAddr = addr ?? { addrBook.peers.reject({|peer| peer == addrBook[addrBook.me.name] }).detect({|peer| peer.online }).addr };
```

…so that we're not relying on the addrBook.me at all. But this is not a good long term solution. In general, we're confused as to why the local IP needs be added to the address book at all. Shouldn't the address book only ever contain remote address?

You can check the basic problem for yourself by running the code from Examples.scd:

```
(
~win = Window("AdHocSociety").front;
~win.layout = VLayout.new.add(~listView = ListView.new);

~addrBook = AddrBook.new;
// to get updates, just add a dependant
~addrBook.addDependant({|addrBook, what, who|
    {~listView.items = addrBook.peers.collectAs({|peer|
        peer.name ++ " | " ++ peer.addr.ip ++ " | " ++ if(peer.online, "online", "offline");
    }, Array)}.defer;
});

~addrBook.addMe; // will automatically add you using your user name

~hail = Hail(~addrBook);
)
```

Then executing these lines:

```
~addrBook.me // returns local address
~addrBook[~addrBook.me.name] // returns the remote address contained at the same name
```

The broader question is, why does addrBook.me have to be defined at all before Hailing. Why not only define it once the hail-reply has been received?

Cheers,
Jonas and Graham

**Comment by muellmusik** [comment]
> But I think the remaining issue is that ~addrBook.me is not the same Peer object as ~addrBook[~addrBook.me.name]. Normally this is not a problem, but if somebody tested for identity rather than equivalence, it would fail.

Okay, I fixed this with PR #10 and b681ebc.

One remaining query. I am tempted to add an additional OSCFunc in Hail (and similar in registrant) like so:
```
OSCFunc({|msg, time, addr|
	addrBook.me.addr = addr; 
	addrBook.me.changed(\addr);
}, oscPath, recvPort: addrBook.me.addr.port, argTemplate: [nil, addrBook.me.name]).oneShot;
```
This would update the internal address to the match the externally visible one. Any reason not to do this? Is there any performance difference in sending to localhost rather than an equivalent address?

**Comment by muellmusik** [comment]
> This would update the internal address to the match the externally visible one.

Sorry, which can be useful for display purposes for instance.

**Comment by muellmusik** [comment]
I think this is actually all resolved now. Any reason not to close?

**Comment by telephon** [comment]
thanks!!
